package com.mainsteam.stm.webService.cmdb.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-05-29T13:42:00.467+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "ConfigInfoMOserviceBusImplService", 
                  targetNamespace = "http://impl.server.webservice.ms.com/")
public class ConfigInfoMOserviceBusImplService extends Service {
	
    public final static QName SERVICE = new QName("http://impl.server.webservice.ms.com/", "ConfigInfoMOserviceBusImplService");
    public final static QName ConfigInfoMOserviceBusImplPort = new QName("http://impl.server.webservice.ms.com/", "ConfigInfoMOserviceBusImplPort");
    public ConfigInfoMOserviceBusImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConfigInfoMOserviceBusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigInfoMOserviceBusImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigInfoMOserviceBusImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MoServiceBus
     */
    @WebEndpoint(name = "ConfigInfoMOserviceBusImplPort")
    public MoServiceBus getConfigInfoMOserviceBusImplPort() {
        return super.getPort(ConfigInfoMOserviceBusImplPort, MoServiceBus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoServiceBus
     */
    @WebEndpoint(name = "ConfigInfoMOserviceBusImplPort")
    public MoServiceBus getConfigInfoMOserviceBusImplPort(WebServiceFeature... features) {
        return super.getPort(ConfigInfoMOserviceBusImplPort, MoServiceBus.class, features);
    }

}
