package com.mainsteam.stm.webService.cmdb.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14 2015-05-29T13:42:00.453+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://www.mainsteam.com/ms", name = "moServiceBus")
@XmlSeeAlso({ ObjectFactory.class })
public interface MoServiceBus {

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "sendMos", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.SendMos")
	@WebMethod
	@ResponseWrapper(localName = "sendMosResponse", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.SendMosResponse")
	public String sendMos(
			@WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0)
			throws WSException;
}
