
package com.mainsteam.stm.webService.cmdb.client;

import javax.xml.ws.WebFault;

import com.mainsteam.stm.webService.cmdb.client.cms.schemas.WsException;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-05-29T13:42:00.439+08:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "wsException", targetNamespace = "www.mainsteam.com/ms/cms/schemas/")
public class WSException extends Exception {
    
    private WsException wsException;

    public WSException() {
        super();
    }
    
    public WSException(String message) {
        super(message);
    }
    
    public WSException(String message, Throwable cause) {
        super(message, cause);
    }

    public WSException(String message, WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WSException(String message, WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public WsException getFaultInfo() {
        return this.wsException;
    }
}
