	CREATE TABLE STM_INSPECT_PLAN(
		ID BIGINT NOT NULL,
		TASK_NAME VARCHAR(255) COMMENT '巡检任务名称',
		TYPE INT COMMENT '巡检方式',
		DESCRIBLE TEXT COMMENT '描述',
		DOMAIN VARCHAR(255) COMMENT '域ID',
		INSPECTOR BIGINT COMMENT '巡检人ID',
		REPORT_PRODUCE_TIME_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示报告生成时间',
		REPORT_MODIFY_TIME_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示报告最后编辑时间',
		REPORT_MODIFIOR_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示最后编辑人',
		REPORT_EDITABLE BOOLEAN DEFAULT FALSE COMMENT '是否允许报表内容被手动修改',
		RESOURCE_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示资源內型',
		BUSINESS_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示业务內型',
		RESOURCE_NAME VARCHAR(255) COMMENT '资源类型名称的ID',
		RESOURCE_TYPE VARCHAR(255) COMMENT '资源类型ID',
		BUSINESS_NAME VARCHAR(255) COMMENT '业务名称的ID',
		STATUS BOOLEAN DEFAULT TRUE COMMENT '状态（是否启用）',
		CREATOR BIGINT COMMENT '创建人ID',
		LAST_EDIT_TIME TIMESTAMP DEFAULT NOW() COMMENT '最后编辑时间',
		TYPE_TIME TEXT COMMENT '如果为自动，存一个时间JSON字符串',
		LAST_EXEC_TIME TIMESTAMP COMMENT '最后执行时间',
		REPORT_NAME VARCHAR(255) COMMENT '报告名称',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_PLAN COMMENT='巡检计划基本信息表';
	CREATE TABLE STM_INSPECT_PLAN_SELF_ITEM(
		ID BIGINT NOT NULL,
		INSPECT_PLAN_ID BIGINT NOT NULL COMMENT '表外键，关联到INSPECT_PLAN表的主键',
		SELF_ITEM_NAME VARCHAR(255) COMMENT '自定义的名称',
		SELF_ITME_TYPE INT COMMENT '自定义的类型',
		ITEM_CONTENT TEXT COMMENT '自定义内容',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_PLAN_SELF_ITEM COMMENT='巡检计划自定义选项表';
	CREATE TABLE STM_INSPECT_PLAN_CONTENT(
		ID BIGINT NOT NULL,
		INSPECT_PLAN_ID BIGINT COMMENT '外键，关联到INSPECT_PLAN表的主键',
		PARENT_ID BIGINT COMMENT '本表父ID',
		CHILD_ITME VARCHAR(255) COMMENT '巡检项',
		ITME_DESCRIBLE VARCHAR(1000) COMMENT '巡检描述',
		ITME_VALUE TEXT COMMENT '巡检值',
		ITME_REFERENCE_PREFIX TEXT COMMENT '参考值前缀',
		ITME_REFERENCE_SUBFIX TEXT COMMENT '参考值后缀',
		ITME_UNIT VARCHAR(255) COMMENT '单位',
		ITME_CONDITION_DESCRIBLE TEXT COMMENT '情况概要',
		SORT INT DEFAULT 0 COMMENT '排序',
		EDIT BOOLEAN DEFAULT FALSE COMMENT '是否是检查项',
		INDICATOR_AS_ITEM BOOLEAN DEFAULT FALSE COMMENT '是否是指标作为巡检项',
		RESOURCE_ID BIGINT COMMENT '资源ID',
		INDEX_MODEL_ID VARCHAR(255) COMMENT '指标ID',
		MODEL_ID varchar(255) COMMENT '模型id',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_PLAN_CONTENT COMMENT='巡检计划内容表';
	CREATE TABLE STM_INSPECT_PLAN_RESULT_SETTING(
		ID BIGINT NOT NULL,
		INSPECT_PLAN_ID BIGINT NOT NULL,
		SUMMERISE_NAME VARCHAR(255) COMMENT '结论名称',
		SUMERISE_DESCRIBLE TEXT COMMENT '结论描述',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_PLAN_RESULT_SETTING COMMENT='巡检计划结论设置';

	CREATE TABLE STM_INSPECT_REPORT(
		ID BIGINT NOT NULL,
		DOMAIN VARCHAR(255) COMMENT '域名称',
		INSPECTOR VARCHAR(255) COMMENT '巡检人',
		PRODUCE_TIME_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示报告生成时间',
		PRODUCE_TIME DATETIME NOT NULL COMMENT '报告生成时间',
		MODIFY_TIME_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示报告最后编辑时间',
		EDIT_TIME DATETIME COMMENT '报告最后编辑时间',
		MODIFIOR_SHOW BOOLEAN DEFAULT FALSE COMMENT '是否显示最后编辑人',
		EDIT_USER_NAME VARCHAR(255) COMMENT '最后编辑人',
		RESOURCE_NAME VARCHAR(255) COMMENT '资源类型名称',
		BUSINESS_NAME VARCHAR(255) COMMENT '业务名称',
		STATUS BOOLEAN DEFAULT FALSE COMMENT '状态（是否提交）',
		TASK_CREATOR VARCHAR(255) COMMENT '创建人',
		SUBMIT_TIME DATETIME COMMENT '报告提交时间',
		NAME VARCHAR(255) COMMENT '巡检报告名称',
		TASK VARCHAR(255) COMMENT '巡检计划名称',
		EDIT BOOLEAN DEFAULT FALSE COMMENT '是否允许修改报告',
		PLAN_ID BIGINT COMMENT '计划id',
		CREATOR_ID BIGINT COMMENT '创建人id',
		INSPECTOR_ID BIGINT COMMENT '巡检人id',
		UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_REPORT COMMENT='巡检报表基本信息表';
	CREATE TABLE STM_INSPECT_REPORT_SELF_ITEM(
		ID BIGINT NOT NULL,
		INSPECT_REPORT_ID BIGINT NOT NULL,
		SELF_ITEM_NAME VARCHAR(255) COMMENT '自定义的名称',
		SELF_ITME_TYPE INT COMMENT '自定义的类型',
		ITEM_CONTENT VARCHAR(255) COMMENT '自定义内容',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_REPORT_SELF_ITEM COMMENT='巡检报告自定义选项表';
	CREATE TABLE STM_INSPECT_REPORT_CONTENT(
		ID BIGINT NOT NULL,
		INSPECT_REPORT_ID BIGINT,
		PARENT_ID BIGINT COMMENT '本表父ID',
		CHILD_ITME VARCHAR(255) COMMENT '名称',
		ITEM_DESCRIBLE TEXT COMMENT '描述',
		ITEM_VALUE TEXT COMMENT '巡检值',
		ITEM_REFERENCE_PREFIX TEXT COMMENT '参考值前缀',
		ITEM_REFERENCE_SUBFIX TEXT COMMENT '参考值后缀',
		ITEM_UNIT VARCHAR(255) COMMENT '单位',
		ITEM_CONDITION_DESCRIBLE TEXT COMMENT '情况概要',
		ITEM_RESULT BOOLEAN DEFAULT FALSE COMMENT '结果',
		EDIT BOOLEAN DEFAULT FALSE COMMENT '是否是检查项',
		INDICATOR_AS_ITEM BOOLEAN DEFAULT FALSE COMMENT '是否是指标作为巡检项',
		TYPE INT COMMENT '类型：1、手动，2、自动',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_REPORT_CONTENT COMMENT='巡检报告内容表';
	CREATE TABLE STM_INSPECT_REPORT_SUMMARIES_SETTING(
		ID BIGINT NOT NULL,
		INSPECT_REPORT_ID BIGINT NOT NULL,
		SUMMERISE_NAME VARCHAR(255) COMMENT '结论名称',
		SUMERISE_DESCRIBLE TEXT COMMENT '结论描述',
		primary key(ID)
	);
	ALTER TABLE STM_INSPECT_REPORT_SUMMARIES_SETTING COMMENT='巡检报告结论设置';