
package com.mainsteam.ms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.ms.webservice.server.impl.ConfigItemMOServiceBusImplService;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-05-29T13:42:00.365+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class MoServiceBus_ConfigItemMOServiceBusImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.server.webservice.ms.com/", "ConfigItemMOServiceBusImplService");

    private MoServiceBus_ConfigItemMOServiceBusImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConfigItemMOServiceBusImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConfigItemMOServiceBusImplService ss = new ConfigItemMOServiceBusImplService(wsdlURL, SERVICE_NAME);
        MoServiceBus port = ss.getConfigItemMOServiceBusImplPort();  
        
        {
        System.out.println("Invoking sendMoAttributeValue...");
        java.lang.String _sendMoAttributeValue_arg0 = "123";
        try {
            port.sendMoAttributeValue(_sendMoAttributeValue_arg0);

        } catch (WSException e) { 
            System.out.println("Expected exception: WSException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
