
package com.mainsteam.ms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-05-29T13:42:00.439+08:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "wsException", targetNamespace = "www.mainsteam.com/ms/cms/schemas/")
public class WSException extends Exception {
    
    private com.mainsteam.ms.cms.schemas.WsException wsException;

    public WSException() {
        super();
    }
    
    public WSException(String message) {
        super(message);
    }
    
    public WSException(String message, Throwable cause) {
        super(message, cause);
    }

    public WSException(String message, com.mainsteam.ms.cms.schemas.WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WSException(String message, com.mainsteam.ms.cms.schemas.WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public com.mainsteam.ms.cms.schemas.WsException getFaultInfo() {
        return this.wsException;
    }
}
