package com.ms.webservice.server.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.mainsteam.ms.MoServiceBus;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-05-29T13:42:00.467+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "ConfigItemMOServiceBusImplService", 
                  wsdlLocation = "http://192.168.1.207:9080/cms/schemas/moservicews?wsdl",
                  targetNamespace = "http://impl.server.webservice.ms.com/")
public class ConfigItemMOServiceBusImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.webservice.ms.com/", "ConfigItemMOServiceBusImplService");
    public final static QName ConfigItemMOServiceBusImplPort = new QName("http://impl.server.webservice.ms.com/", "ConfigItemMOServiceBusImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.207:9080/cms/schemas/moservicews?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConfigItemMOServiceBusImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.207:9080/cms/schemas/moservicews?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConfigItemMOServiceBusImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConfigItemMOServiceBusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfigItemMOServiceBusImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigItemMOServiceBusImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigItemMOServiceBusImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigItemMOServiceBusImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MoServiceBus
     */
    @WebEndpoint(name = "ConfigItemMOServiceBusImplPort")
    public MoServiceBus getConfigItemMOServiceBusImplPort() {
        return super.getPort(ConfigItemMOServiceBusImplPort, MoServiceBus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoServiceBus
     */
    @WebEndpoint(name = "ConfigItemMOServiceBusImplPort")
    public MoServiceBus getConfigItemMOServiceBusImplPort(WebServiceFeature... features) {
        return super.getPort(ConfigItemMOServiceBusImplPort, MoServiceBus.class, features);
    }

}
