<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="itssAlarmServiceBus" targetNamespace="http://www.mainsteam.com/ms" xmlns:ns1="http://www.mainsteam.com/ms" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xs:schema elementFormDefault="unqualified" targetNamespace="http://www.mainsteam.com/ms" version="1.0" xmlns:tns="http://www.mainsteam.com/ms" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="sendAlarms" type="tns:sendAlarms"/>
      <xs:element name="sendAlarmsResponse" type="tns:sendAlarmsResponse"/>
      <xs:complexType name="sendAlarms">
        <xs:sequence>
          <xs:element minOccurs="0" name="arg0" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="sendAlarmsResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="sendAlarms">
    <wsdl:part element="ns1:sendAlarms" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="sendAlarmsResponse">
    <wsdl:part element="ns1:sendAlarmsResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="itssAlarmServiceBus">
    <wsdl:operation name="sendAlarms">
      <wsdl:input message="ns1:sendAlarms" name="sendAlarms"/>
      <wsdl:output message="ns1:sendAlarmsResponse" name="sendAlarmsResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>