package com.mainsteam.stm.alarm.soap.itsm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-10T10:54:38.554+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://www.mainsteam.com/ms", name = "itssAlarmServiceBus")
@XmlSeeAlso({ObjectFactory.class})
public interface ItssAlarmServiceBus {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendAlarms", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.alarm.soap.itsm.SendAlarms")
    @WebMethod
    @ResponseWrapper(localName = "sendAlarmsResponse", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.alarm.soap.itsm.SendAlarmsResponse")
    public java.lang.String sendAlarms(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
