package com.mainsteam.stm.alarm.soap.itsm;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-10T10:54:38.569+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "ITSSAlarmServiceBusImplService", 
                  wsdlLocation = "file:/C:/Users/pc/AppData/Local/Temp/tempdir5563375007960925581.tmp/alarm_1.wsdl",
                  targetNamespace = "http://impl.service.itss.itsm.onecenter.chinawiserv.com/")
public class ITSSAlarmServiceBusImplService extends Service {

    //http://impl.service.itss.itsm.onecenter.chinawiserv.com/
    //http://impl.service.itss.stsm.ms.mainsteam.com/
    public final static QName SERVICE = new QName("http://impl.service.itss.itsm.onecenter.chinawiserv.com/", "ITSSAlarmServiceBusImplService");
    public final static QName ITSSAlarmServiceBusImplPort = new QName("http://impl.service.itss.itsm.onecenter.chinawiserv.com/", "ITSSAlarmServiceBusImplPort");

    public ITSSAlarmServiceBusImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ITSSAlarmServiceBusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITSSAlarmServiceBusImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITSSAlarmServiceBusImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ItssAlarmServiceBus
     */
    @WebEndpoint(name = "ITSSAlarmServiceBusImplPort")
    public ItssAlarmServiceBus getITSSAlarmServiceBusImplPort() {
        return super.getPort(ITSSAlarmServiceBusImplPort, ItssAlarmServiceBus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItssAlarmServiceBus
     */
    @WebEndpoint(name = "ITSSAlarmServiceBusImplPort")
    public ItssAlarmServiceBus getITSSAlarmServiceBusImplPort(WebServiceFeature... features) {
        return super.getPort(ITSSAlarmServiceBusImplPort, ItssAlarmServiceBus.class, features);
    }

}
