package com.mainsteam.stm.webService.user.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-06-04T09:49:49.842+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.mainsteam.com/ms", name = "baseInfoServiceBus")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceApi {
    @RequestWrapper(localName = "setUser", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.webService.user.client.SetUser")
    @WebMethod
    @ResponseWrapper(localName = "setUserResponse", targetNamespace = "http://www.mainsteam.com/ms", className = "com.mainsteam.stm.webService.user.client.SetUserResponse")
    public void setUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WSException;
}
