
package com.mainsteam.stm.webService.user.client;

import javax.xml.ws.WebFault;

import com.mainsteam.stm.webService.cmdb.client.cms.schemas.WsException;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-06-04T09:49:49.822+08:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "wsException", targetNamespace = "http://www.mainsteam.com/ms")
public class WSException extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 5373243393209804299L;
	private WsException wsException;

    public WSException() {
        super();
    }
    
    public WSException(String message) {
        super(message);
    }
    
    public WSException(String message, Throwable cause) {
        super(message, cause);
    }

    public WSException(String message, WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WSException(String message, WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public WsException getFaultInfo() {
        return this.wsException;
    }
}
